import{a as u}from"./assets/vendor-34f890c2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const f="https://api.themoviedb.org/3",m="/trending/movie/week",p="345007f9ab440e5b86cef51be6397df1";let c=1;const s={container:document.querySelector(".js-movie-list"),loadBtn:document.querySelector(".js-load-more")};s.loadBtn.addEventListener("click",g);d(c).then(t=>{s.container.insertAdjacentHTML("beforeend",l(t.results)),t.page<500&&s.loadBtn.classList.replace("load-more-hidden","load-more")}).catch(t=>alert(t.message));async function d(t=1){const{data:r}=await u(`${f}${m}`,{params:{api_key:p,page:t}});return r}function l(t){return t.map(({id:r,poster_path:n,original_title:a,release_date:e,vote_average:o})=>`
     <li class="movie-card" data-id="${r}">
        <img src="https://image.tmdb.org/t/p/w300${n}" alt="${a}">
        <div class="movie-info"></div>
        <h2>${a}</h2>
        <p>Release Date: ${e}</p>
        <p>Vote Average: ${o}</p>
    </li>`).join("")}async function g(){c+=1,s.loadBtn.disabled=!0;try{const t=await d(c);s.container.insertAdjacentHTML("beforeend",l(t.results)),s.loadBtn.disabled=!1;const n=document.querySelector(".movie-card").getBoundingClientRect().height;window.scrollBy({left:0,top:n*2,behavior:"smooth"}),t.page<500&&s.loadBtn.classList.replace("load-more","load-more-hidden")}catch(t){alert(t.message)}}
//# sourceMappingURL=commonHelpers.js.map
